title: David Sutton
description: Interactive Design and User Experience
show_downloads: true
google_analytics: UA-120055911-1
#theme: jekyll-theme-slate
remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-include-cache
